---
title: "From Data to Masterpiece: Exploring the Beauty of Scatter Plot Visualization for Biomedical Research with ggplot2" 
author: Tope A Ibisanmi
date: 16 June 2023
output: 
  html_document: 
    keep_md: yes 
    toc: true  
    toc_depth: 4
    toc_float: 
      collapsed: false 
      smooth_scroll: true
    theme: flatly  
    highlight: pygments 
---  



```{r, echo = F}
#Install and load ggplot2
#install.packages('ggplot2')
library(ggplot2)
# Create a folder named "images"
dir.create("results")

```  





```{r EGFR}

#for EGFR
# Load required packages
library(ggplot2)
# Data
MMGBSA <- c(-50.710, -50.259, -46.969, -54.282, -29.207, -58.001, -41.030, -43.614, -35.381, -46.151, -49.371, -48.520, -34.601, -41.861, -44.773, -48.783, -47.583, -43.556, -55.224, -21.193, -101.290)
DOCK_SCORES <- c(-8.409, -7.287, -9.430, -8.392, -9.134, -9.177, -9.453, -6.953, -7.132, -10.730, -8.366, -8.228, -7.522, -8.537, -9.165, -11.016, -8.671, -7.452, -9.968, -3.150, -13.652)

# Create a data frame
data <- data.frame(MMGBSA, DOCK_SCORES)

# Plotting
EGFRplot <- ggplot(data, aes(x = MMGBSA, y = DOCK_SCORES)) +
  geom_point(size = 4, color = "steelblue", alpha = 0.8) +
  geom_smooth(method = "lm", color = "red", se = FALSE, linetype = "dashed") +
  labs(
    x = "MMGBSA (DeltaGbind)",
    y = "Docking Scores (kcal/mol)",
    title = "                  Binding Free Energy vs Docking Scores (EGFR)",
    caption = "Data Source: EGFR"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white")
  )

# Print the plot
print(EGFRplot)

# Save the plot in the /results directory
ggsave("results/EGFRplot.jpg", plot = EGFRplot, width = 8, height = 6, dpi = 300)



```






```{r IGFR}

#IGFR

# Load required packages
library(ggplot2)
# Data
MMGBSA <- c(-43.937, -42.048, -37.008, -46.188, -54.695, -51.520, -36.923, -48.414, -56.882, -52.535, -41.153, -27.309, -37.708, -36.099, -41.432, -50.784, -44.509, -35.092, -46.287, -12.783, -47.934)
DOCK_SCORES <- c(-8.924, -9.435, -7.145, -11.418, -9.284, -9.672, -6.514, -10.257, -14.224, -10.528, -7.195, -6.736, -8.833, -9.487, -9.998, -11.720, -9.906, -6.759, -7.348, -5.678, -10.235)

# Create a data frame
data <- data.frame(MMGBSA, DOCK_SCORES)

# Plotting
IGFRplot <- ggplot(data, aes(x = MMGBSA, y = DOCK_SCORES)) +
  geom_point(size = 4, color = "steelblue", alpha = 0.8) +
  geom_smooth(method = "lm", color = "red", se = FALSE, linetype = "dashed") +
  labs(
    x = "MMGBSA (DeltaGbind)",
    y = "Docking Scores (kcal/mol)",
     title = "                  Binding Free Energy vs Docking Scores (IGFR)",
    caption = "Data Source: IGFR"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white")
  )

# Print the plot
print(IGFRplot)

# Save the plot in the /results directory
ggsave("results/IGFRplot.jpg", plot = IGFRplot, width = 8, height = 6, dpi = 300)



```





```{r ESR}
#ESR


# Load required packages

library(ggplot2)

# Sample data
MMGBSA <- c(-37.160, -43.353, -45.151, -38.490, -47.675, -41.506, -38.376, -48.263, -23.531, -43.848, -42.937, -29.817, -36.616, 14.249, -33.091, -42.810, -42.498, -44.795, -44.276, -38.435, -96.555)
DOCK_SCORES <- c(-9.802, -8.635, -7.935, -8.238, -9.731, -9.108, -9.169, -8.614, -6.757, -9.317, -10.152, -9.646, -7.527, -9.011, -8.775, -7.624, -8.861, -9.406, -8.829, -3.751, -12.940)

# Create a data frame
data <- data.frame(MMGBSA, DOCK_SCORES)

# Plotting
ESRplot <- ggplot(data, aes(x = MMGBSA, y = DOCK_SCORES)) +
  geom_point(size = 4, color = "steelblue", alpha = 0.8) +
  geom_smooth(method = "lm", color = "red", se = FALSE, linetype = "dashed") +
  labs(
    x = "MMGBSA (DeltaGbind)",
    y = "Docking Scores (kcal/mol)",
     title = "                  Binding Free Energy vs Docking Scores (ESR)",
    caption = "Data Source: ESR"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white")
  )

# Print the plot
print(ESRplot)

# Save the plot in the /results directory
ggsave("results/ESRplot.jpg", plot = ESRplot, width = 8, height = 6, dpi = 300)



```




```{r PGR}
#PGR


# Load required packages

library(ggplot2)

# Data
MMGBSA <- c(-54.617, -61.403, -57.418, -50.688, -28.483, -52.050, -45.904, -50.496, 42.824, -24.662, -49.588, -53.909, -52.416, -55.983, 4.578, -41.190, -47.654, -29.783, -55.996, -56.724, -54.061, -30.900, -68.493)
DOCK_SCORES <- c(-9.664, -8.484, -11.655, -10.544, -11.756, -11.362, -9.515, -9.388, -10.933, -6.913, -11.230, -9.664, -10.140, -9.825, -9.946, -7.603, -10.497, -8.658, -9.251, -12.462, -10.141, -9.895, -11.023)

# Create a data frame
data <- data.frame(MMGBSA, DOCK_SCORES)

# Plotting
PGRplot <- ggplot(data, aes(x = MMGBSA, y = DOCK_SCORES)) +
  geom_point(size = 4, color = "steelblue", alpha = 0.8) +
  geom_smooth(method = "lm", color = "red", se = FALSE, linetype = "dashed") +
  labs(
    x = "MMGBSA (DeltaGbind)",
    y = "Docking Scores (kcal/mol)",
     title = "                  Binding Free Energy vs Docking Scores (PGR)",
    caption = "Data Source: PGR"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white")
  )

# Print the plot
print(PGRplot)

# Save the plot in the /results directory
ggsave("results/PGRplot.jpg", plot = PGRplot, width = 8, height = 6, dpi = 300)



```



```{r YAP1}
#YAP1


# Load required packages

# Data
MMGBSA <- c(-35.407, -44.828, -31.373, -38.629, 6.928, -26.013, -30.560, -37.855, -20.505, -33.396, -20.387, -25.250, -14.341, -17.709, -41.659, 6.437, -38.297, -28.954, 0.670, -53.366)
DOCK_SCORES <- c(-8.027, -9.182, -9.305, -10.019, -6.728, -8.503, -7.471, -9.074, -6.922, -8.894, -8.238, -8.620, -9.029, -8.063, -8.586, -8.079, -8.534, -6.530, 0.046, -8.316)
# Create a data frame
data <- data.frame(MMGBSA, DOCK_SCORES)

# Plotting
YAP1plot <- ggplot(data, aes(x = MMGBSA, y = DOCK_SCORES)) +
  geom_point(size = 4, color = "steelblue", alpha = 0.8) +
  geom_smooth(method = "lm", color = "red", se = FALSE, linetype = "dashed") +
  labs(
    x = "MMGBSA (DeltaGbind)",
    y = "Docking Scores (kcal/mol)",
     title = "                  Binding Free Energy vs Docking Scores (YAP1)",
    caption = "Data Source: YAP1"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white")
  )

# Print the plot
print(YAP1plot)

# Save the plot in the /results directory
ggsave("results/YAP1plot.jpg", plot = YAP1plot, width = 8, height = 6, dpi = 300)



```  

